### ISSUE TITLE
Unspecified dependency

### ISSUE THREAD

**Issue by jbrucker** [boom210232/blackdesert-DAO#3]
Your app requires matplotlib but it is not in requirements.txt.

You should install your own app in a virtualenv so you can 
find the actual dependencies.

**Comment by jbrucker** [comment]
Installing matplotlib also installs several indirect dependencies.

**Comment by boom210232** [comment]
Apologise for late reply, Maybe because I use my setting venv (it has too many dependencies package, also it quite heavy in my local machine too.) I will fix this ASAP.

**Comment by boom210232** [comment]
I decide to remove it. Because in terminal UI, we see the result in acceptable level and not necessary for now.
