### ISSUE TITLE
'main.py' fails with syntax error

### ISSUE THREAD

**Issue by jbrucker** [boom210232/blackdesert-DAO#4]
After installing dependencies, when I execute main.py, Python show:
```
  File "main.py", line 8, in <module>
    print(bdo_starter.market_list().get_all_market_transaction())
TypeError: market_list() missing 1 required positional argument: 'self'
```

The root cause is a different syntax error in main.py

**Comment by jbrucker** [comment]
After I fixed the above syntax error, I get errors from SqlAlchemy.
Looks like your code isn't done yet.

**Comment by boom210232** [comment]
I'm finish to fix on this error. Thank you for your advice prof.James.
